-- Create tasks table for task management
CREATE TABLE tasks (
    task_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD') NOT NULL DEFAULT 'PENDING',
    priority ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') NOT NULL DEFAULT 'MEDIUM',
    type ENUM('GENERAL', 'CALL', 'EMAIL', 'MEETING', 'FOLLOW_UP', 'DEMO', 'PROPOSAL', 'CONTRACT', 'RESEARCH', 'ADMINISTRATIVE') NOT NULL DEFAULT 'GENERAL',
    assigned_to_user_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    due_date DATETIME,
    completed_at DATETIME,
    related_contact_id BIGINT,
    related_account_id BIGINT,
    related_deal_id BIGINT,
    related_lead_id BIGINT,
    related_entity_type VARCHAR(50),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_tasks_tenant_id (tenant_id),
    INDEX idx_tasks_assigned_to_user_id (assigned_to_user_id),
    INDEX idx_tasks_created_by_user_id (created_by_user_id),
    INDEX idx_tasks_status (status),
    INDEX idx_tasks_priority (priority),
    INDEX idx_tasks_type (type),
    INDEX idx_tasks_due_date (due_date),
    INDEX idx_tasks_related_contact_id (related_contact_id),
    INDEX idx_tasks_related_account_id (related_account_id),
    INDEX idx_tasks_related_deal_id (related_deal_id),
    INDEX idx_tasks_related_lead_id (related_lead_id),
    INDEX idx_tasks_created_at (created_at),
    INDEX idx_tasks_tenant_status (tenant_id, status),
    INDEX idx_tasks_tenant_assigned (tenant_id, assigned_to_user_id),
    INDEX idx_tasks_tenant_due_date (tenant_id, due_date),
    INDEX idx_tasks_overdue (tenant_id, due_date, status)
);
